version: "3.9"
services:
  postgres:
    image: postgres:9.6-bullseye
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
  pgAdmin:
    image: dpage/pgadmin4:6.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=1
    ports:
      - 80:80